// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_analytics is a generated GoMock package.
package mock_analytics

import (
	context "context"
	reflect "reflect"

	db "github.com/avraam311/url-shortener/internal/models/db"
	dto "github.com/avraam311/url-shortener/internal/models/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockRepositoryAnalytics is a mock of RepositoryAnalytics interface.
type MockRepositoryAnalytics struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryAnalyticsMockRecorder
}

// MockRepositoryAnalyticsMockRecorder is the mock recorder for MockRepositoryAnalytics.
type MockRepositoryAnalyticsMockRecorder struct {
	mock *MockRepositoryAnalytics
}

// NewMockRepositoryAnalytics creates a new mock instance.
func NewMockRepositoryAnalytics(ctrl *gomock.Controller) *MockRepositoryAnalytics {
	mock := &MockRepositoryAnalytics{ctrl: ctrl}
	mock.recorder = &MockRepositoryAnalyticsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryAnalytics) EXPECT() *MockRepositoryAnalyticsMockRecorder {
	return m.recorder
}

// GetAnalytics mocks base method.
func (m *MockRepositoryAnalytics) GetAnalytics(arg0 context.Context, arg1 string) ([]*db.Analytics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnalytics", arg0, arg1)
	ret0, _ := ret[0].([]*db.Analytics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnalytics indicates an expected call of GetAnalytics.
func (mr *MockRepositoryAnalyticsMockRecorder) GetAnalytics(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnalytics", reflect.TypeOf((*MockRepositoryAnalytics)(nil).GetAnalytics), arg0, arg1)
}

// SaveAnalytics mocks base method.
func (m *MockRepositoryAnalytics) SaveAnalytics(arg0 context.Context, arg1 *dto.Analytics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAnalytics", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAnalytics indicates an expected call of SaveAnalytics.
func (mr *MockRepositoryAnalyticsMockRecorder) SaveAnalytics(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAnalytics", reflect.TypeOf((*MockRepositoryAnalytics)(nil).SaveAnalytics), arg0, arg1)
}
